---
- name: Test a test test
  command: echo pwd

- name: Make script executable
  file: path=/vagrant/ansible/roles/vagrant/files/create_tables.sh mode="a+x"
  
- name: Create postgres tables
  command: /vagrant/ansible/roles/vagrant/files/create_tables.sh
  become: yes
  become_user: root
